# Generated by Django 5.0.3 on 2024-04-09 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors_record', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='acknowledgment_date',
            new_name='acknowledgement_date',
        ),
    ]
