# Generated by Django 5.0.3 on 2024-04-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors_record', '0002_rename_acknowledgment_date_purchaseorder_acknowledgement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='vendor',
            field=models.CharField(max_length=255),
        ),
    ]
